# Generated by Django 5.0.2 on 2024-12-10 09:54

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BHAComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('component_type', models.CharField(choices=[('DRILL_COLLAR', 'Drill Collar'), ('STABILIZER', 'Stabilizer'), ('REAMER', 'Reamer'), ('SHOCK', 'Shock'), ('HOLE_OPENER', 'Hole Opener'), ('BIT_SUB', 'Bit Sub'), ('BIT', 'Bit')], max_length=20)),
                ('length', models.FloatField(validators=[django.core.validators.MinValueValidator(0.1)])),
                ('diameter', models.FloatField(validators=[django.core.validators.MinValueValidator(0.1)])),
                ('image', models.ImageField(blank=True, null=True, upload_to='bha_components/')),
                ('manufacturer', models.CharField(blank=True, max_length=100, null=True)),
                ('weight', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
            ],
        ),
        migrations.CreateModel(
            name='BHAConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('total_length', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='BHAConfigurationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('order', models.PositiveIntegerField()),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bha_app.bhacomponent')),
                ('configuration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='bha_app.bhaconfiguration')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
