# Generated by Django 5.0.2 on 2024-12-10 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bha_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bhaconfiguration',
            name='bha_image',
            field=models.ImageField(blank=True, null=True, upload_to='bha_configurations/'),
        ),
    ]
